version: '2'
services:
    jhipstersamplemonolith-app:
        image: jhipstersamplemonolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersamplemonolith-postgresql:5432/jhipsterSampleMonolith
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersamplemonolith-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersamplemonolith-postgresql
